# Generated by Django 6.0.2 on 2026-05-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_address_user_pickup_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_female',
            field=models.BooleanField(default=False),
        ),
    ]
