# Generated by Django 6.0.2 on 2026-08-03 04:58
import os

from django.contrib.auth.hashers import make_password
from django.db import migrations


def create_render_admin(apps, schema_editor):
    User = apps.get_model("accounts", "User")

    username = os.environ.get("DJANGO_SUPERUSER_USERNAME")
    email = os.environ.get("DJANGO_SUPERUSER_EMAIL", "")
    password = os.environ.get("DJANGO_SUPERUSER_PASSWORD")

    if not username or not password:
        print("Admin environment variables are missing. Skipping admin creation.")
        return

    user, created = User.objects.get_or_create(
        username=username,
        defaults={
            "email": email,
            "role": "ADMIN",
            "is_active": True,
            "is_staff": True,
            "is_superuser": True,
            "password": make_password(password),
        },
    )

    if not created:
        user.email = email
        user.role = "ADMIN"
        user.is_active = True
        user.is_staff = True
        user.is_superuser = True
        user.password = make_password(password)
        user.save()

    print(f"Render admin '{username}' created or updated successfully.")


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_is_female"),
    ]

    operations = [
        migrations.RunPython(
            create_render_admin,
            migrations.RunPython.noop,
        ),
    ]