# Generated by Django 6.0.2 on 2026-09-05 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_create_render_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupLocationChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_pickup_location', models.CharField(blank=True, max_length=255, null=True)),
                ('old_pickup_latitude', models.FloatField(blank=True, null=True)),
                ('old_pickup_longitude', models.FloatField(blank=True, null=True)),
                ('requested_pickup_location', models.CharField(max_length=255)),
                ('requested_pickup_latitude', models.FloatField()),
                ('requested_pickup_longitude', models.FloatField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_location_change_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_pickup_location_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
