# Generated by Django 6.0.2 on 2026-09-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_pickuplocationchangerequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pickuplocationchangerequest',
            options={'ordering': ['-requested_at']},
        ),
        migrations.AddConstraint(
            model_name='pickuplocationchangerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('employee',), name='one_pending_pickup_location_request_per_employee'),
        ),
    ]
