# Generated by Django 6.0.2 on 2026-09-09 12:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_pickuplocationchangerequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee_id',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Employee ID must start with capital E followed by exactly 4 digits. Example: E0282.', regex='^E\\d{4}$')]),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('PREFER_NOT_TO_SAY', 'Prefer not to say')], default='', max_length=20),
        ),
    ]
