# Generated by Django 6.0.2 on 2026-03-27 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_trip_trip_date_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='trip',
            name='unique_employee_trip_type_per_day',
        ),
    ]
