# Generated by Django 6.0.2 on 2026-03-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_remove_trip_unique_employee_trip_type_per_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routetemplate',
            name='trip_type',
        ),
        migrations.AlterField(
            model_name='routerun',
            name='trip_type',
            field=models.CharField(choices=[('PICKUP', 'Pickup'), ('DROP', 'Drop')], max_length=10),
        ),
    ]
