# Generated by Django 6.0.2 on 2026-05-03 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_routerunstop_arrival_time_routerunstop_is_no_show_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripcancellation',
            name='cancelled_by_role',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='tripcancellation',
            name='declaration_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tripcancellation',
            name='declaration_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
