# Generated by Django 6.0.2 on 2026-05-05 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0009_employeeleave'),
    ]

    operations = [
        migrations.AddField(
            model_name='routerunstop',
            name='delay_warning_sent',
            field=models.BooleanField(default=False),
        ),
    ]
