# Generated by Django 6.0.2 on 2026-08-02 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0013_routerunstop_keep_waiting_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routerun',
            name='completion_notifications_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='routerun',
            name='heading_to_office_notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='routerun',
            name='office_15_min_late_alert_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='routerun',
            name='office_deadline_alert_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='routerun',
            name='start_notifications_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='routerunstop',
            name='arrival_notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='routerunstop',
            name='five_hundred_meter_alert_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='routerunstop',
            name='five_min_alert_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='routerunstop',
            name='hundred_meter_alert_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='routerunstop',
            name='no_show_notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='routerunstop',
            name='one_km_alert_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='routerunstop',
            name='pickup_completed_notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
