# Generated by Django 6.0.2 on 2026-08-17 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0014_routerun_completion_notifications_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routerunstop',
            name='boarded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routerunstop',
            name='is_boarded',
            field=models.BooleanField(default=False),
        ),
    ]
