# Generated by Django 6.0.2 on 2026-08-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0015_routerunstop_boarded_at_routerunstop_is_boarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='routerun',
            name='last_two_drop_alert_sent',
            field=models.BooleanField(default=False),
        ),
    ]
