# Generated by Django 6.0.2 on 2026-08-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0016_routerun_last_two_drop_alert_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='routerun',
            name='drop_cab_ready_notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='routerun',
            name='drop_waiting_notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
