# Generated by Django 6.0.2 on 2026-08-31 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0017_routerun_drop_cab_ready_notification_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickupchat',
            name='driver_last_read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pickupchat',
            name='employee_last_read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
