# Generated by Django 6.0.2 on 2026-09-07 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0018_pickupchat_driver_last_read_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emergencyalert',
            old_name='read_at',
            new_name='resolved_at',
        ),
        migrations.AlterField(
            model_name='emergencyalert',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('RESOLVED', 'Resolved')], default='ACTIVE', max_length=20),
        ),
    ]
