# Generated by Django 6.0.2 on 2026-09-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0019_rename_read_at_emergencyalert_resolved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routerunstop',
            name='employee_late_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
