# Generated by Django 6.0.2 on 2026-09-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0020_routerunstop_employee_late_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='routerunstop',
            name='late_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
