# Generated by Django 6.0.2 on 2026-09-12 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0021_routerunstop_late_seconds'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='routetemplate',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routetemplate',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='driverlocationhistory',
            name='driver',
            field=models.ForeignKey(limit_choices_to={'role': 'DRIVER'}, on_delete=django.db.models.deletion.PROTECT, related_name='location_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emergencyalert',
            name='employee',
            field=models.ForeignKey(limit_choices_to={'role': 'EMPLOYEE'}, on_delete=django.db.models.deletion.PROTECT, related_name='emergency_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeeleave',
            name='employee',
            field=models.ForeignKey(limit_choices_to={'role': 'EMPLOYEE'}, on_delete=django.db.models.deletion.PROTECT, related_name='cab_leaves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pickupchat',
            name='driver',
            field=models.ForeignKey(limit_choices_to={'role': 'DRIVER'}, on_delete=django.db.models.deletion.PROTECT, related_name='driver_pickup_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pickupchat',
            name='employee',
            field=models.ForeignKey(limit_choices_to={'role': 'EMPLOYEE'}, on_delete=django.db.models.deletion.PROTECT, related_name='employee_pickup_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pickupchat',
            name='route_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickup_chats', to='trips.routerun'),
        ),
        migrations.AlterField(
            model_name='pickupchat',
            name='stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickup_chats', to='trips.routerunstop'),
        ),
        migrations.AlterField(
            model_name='pickupchatmessage',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='trips.pickupchat'),
        ),
        migrations.AlterField(
            model_name='pickupchatmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='trip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='review', to='trips.trip'),
        ),
        migrations.AlterField(
            model_name='routerun',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='routerun',
            name='route_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='trips.routetemplate'),
        ),
        migrations.AlterField(
            model_name='routerun',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_runs', to='trips.vehicle'),
        ),
        migrations.AlterField(
            model_name='routerunstop',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='routestop',
            name='employee',
            field=models.ForeignKey(limit_choices_to={'role': 'EMPLOYEE'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='routetemplate',
            name='driver',
            field=models.ForeignKey(limit_choices_to={'role': 'DRIVER'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='routetemplate',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='trips.vehicle'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(limit_choices_to={'role': 'DRIVER'}, on_delete=django.db.models.deletion.PROTECT, related_name='driver_trips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trip',
            name='employee',
            field=models.ForeignKey(limit_choices_to={'role': 'EMPLOYEE'}, on_delete=django.db.models.deletion.PROTECT, related_name='employee_trips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trip',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='trips.vehicle'),
        ),
        migrations.AlterField(
            model_name='tripcancellation',
            name='cancelled_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tripcancellation',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cancellations', to='trips.trip'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='driver',
            field=models.OneToOneField(limit_choices_to={'role': 'DRIVER'}, on_delete=django.db.models.deletion.PROTECT, related_name='vehicle', to=settings.AUTH_USER_MODEL),
        ),
    ]
